cc_test(
  name = "test",
  srcs = [
      "soundex_tests.cc",
      "soundex.h",
  ],  
  copts = [
      "-std=c++20"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
    "@range_v3//:range-v3"
  ],
)


