cc_test(
  name = "test",
  srcs = [
    "get_message_tests.cc",
    "get_message.h",
  ],
  deps = ["@com_google_googletest//:gtest_main"],
)


cc_binary(
  name = "main",
  srcs = [
    "main.cc",
    "get_message.h",
  ],
)