load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//src/canvas/startingpoint:test": "",
        "//src/canvas/startingpoint:main": "",
        "//src/canvas/complete:test": "",
        "//src/canvas/complete:main": "",
        "//src/canvas/fancy:test": "",
        "//src/canvas/fancy:main": "",
        "//src/canvas/janky:test": "",
        "//src/canvas/janky:main": "",
        "//src/fizzbuzz/startingpoint:main": "",
        "//src/fizzbuzz/startingpoint:test": "",
        "//src/fizzbuzz/complete:test": "",
        "//src/fizzbuzz/complete:main": "",
        "//src/fizzbuzz/fancy:test": "",
        "//src/fizzbuzz/fancy:main": "",
        "//src/money/startingpoint:test": "",
        "//src/money/startingpoint:main": "",
        "//src/money/complete-needs-refactoring:test": "",
        "//src/money/complete-needs-refactoring:main": "",
        "//src/pi/startingpoint:main": "",
        "//src/pi/startingpoint:test": "",
        "//src/pi/complete:test": "",
        "//src/pi/complete:main": "",
        "//src/restful-fortune/startingpoint:main": "",
        "//src/restful-fortune/startingpoint:test": "",
        "//src/restful-fortune/complete:test": "",
        "//src/restful-fortune/complete:main": "",
        "//src/soundex/startingpoint:main": "",
        "//src/soundex/startingpoint:test": "",
        "//src/soundex/complete-hippie-style:main": "",
        "//src/soundex/complete-hippie-style:test": "",
        "//src/soundex/complete-textbook-needs-refactoring:main": "",
        "//src/soundex/complete-textbook-needs-refactoring:test": "",
    },
)
