cc_test(
  name = "test",
  srcs = [
      "canvas_tests.cc",
      "canvas.h",
      "turtle.h"
  ],
  deps = ["@com_google_googletest//:gtest_main"],
)


cc_binary(
  name = "main",
  srcs = [
    "main.cc",
  ],
)