cc_test(
  name = "test",
  srcs = [
      "soundex_tests.cc",
      "soundex.h",
  ],  
  copts = [
      "-std=c++20",
      "-fcoroutines"
  ],
  deps = ["@com_google_googletest//:gtest_main"],
)


